import { Cores, ColorCard, ColorShadow } from "../../enums/styles";

export const listM = [
  {
    name: "Albedo",
    image: "/personagens/Albedo.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    name: "Amber",
    image: "/personagens/Amber.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Aloy",
    image: "/personagens/Aloy.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Barbara",
    image: "/personagens/Barbara.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star4Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Bennett",
    image: "/personagens/Bennett.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Diluc",
    image: "/personagens/Diluc.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Diona",
    image: "/personagens/Diona.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Eula",
    image: "/personagens/Eula.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Fischl",
    image: "/personagens/Fischl.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Jean",
    image: "/personagens/Jean.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Kaeya",
    image: "/personagens/Kaeya.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Klee",
    image: "/personagens/Klee.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Lisa",
    image: "/personagens/Lisa.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Mika",
    image: "/personagens/Mika.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Mona",
    image: "/personagens/Mona.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Noelle",
    image: "/personagens/Noelle.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    name: "Razor",
    image: "/personagens/Razor.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Rosaria",
    image: "/personagens/Rosaria.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Sucrose",
    image: "/personagens/Sucrose.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Thoma",
    image: "/personagens/Thoma.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "T(Anemo)",
    image: "/personagens/Traveler.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Venti",
    image: "/personagens/Venti.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
];