import { Cores, ColorCard, ColorShadow } from "../enums/styles";

export const lista = [
  {
    id: 5,
    name: "Albedo",
    image: "/personagens/Albedo.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Alhaitham",
    image: "/personagens/Alhaitham.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "Aloy",
    image: "/personagens/Aloy.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Amber",
    image: "/personagens/Amber.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Ayaka",
    image: "/personagens/Ayaka.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Ayato",
    image: "/personagens/Ayato.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Barbara",
    image: "/personagens/Barbara.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star4Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Beidou",
    image: "/personagens/Beidou.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Bennett",
    image: "/personagens/Bennett.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Candace",
    image: "/personagens/Candace.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star4Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Childe",
    image: "/personagens/Childe.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Chongyun",
    image: "/personagens/Chongyun.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Collei",
    image: "/personagens/Collei.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "Cyno",
    image: "/personagens/Cyno.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Dehya",
    image: "/personagens/Dehya.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Diluc",
    image: "/personagens/Diluc.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Diona",
    image: "/personagens/Diona.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Dori",
    image: "/personagens/Dori.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Eula",
    image: "/personagens/Eula.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Faruzan",
    image: "/personagens/Faruzan.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Fischl",
    image: "/personagens/Fischl.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Ganyu",
    image: "/personagens/Ganyu.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Gorou",
    image: "/personagens/Gorou.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Heizou",
    image: "/personagens/Heizou.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Hu Tao",
    image: "/personagens/Hu Tao.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Itto",
    image: "/personagens/Itto.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Jean",
    image: "/personagens/Jean.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Kaeya",
    image: "/personagens/Kaeya.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Kazuha",
    image: "/personagens/Kazuha.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Keqing",
    image: "/personagens/Keqing.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Klee",
    image: "/personagens/Klee.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Kokomi",
    image: "/personagens/Kokomi.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Kuki Shinobu",
    image: "/personagens/Kuki Shinobu.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Layla",
    image: "/personagens/Layla.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Lisa",
    image: "/personagens/Lisa.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Mika",
    image: "/personagens/Mika.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Mona",
    image: "/personagens/Mona.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Nahida",
    image: "/personagens/Nahida.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "Nilou",
    image: "/personagens/Nilou.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Ningguang",
    image: "/personagens/Ningguang.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Noelle",
    image: "/personagens/Noelle.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Qiqi",
    image: "/personagens/Qiqi.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Raiden",
    image: "/personagens/Raiden.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Razor",
    image: "/personagens/Razor.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Rosaria",
    image: "/personagens/Rosaria.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Sara",
    image: "/personagens/Sara.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "Sayu",
    image: "/personagens/Sayu.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Shenhe",
    image: "/personagens/Shenhe.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    id: 5,
    name: "Sucrose",
    image: "/personagens/Sucrose.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Thoma",
    image: "/personagens/Thoma.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Tighnari",
    image: "/personagens/Tighnari.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "T(Anemo)",
    image: "/personagens/Traveler.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "T(Dendro)",
    image: "/personagens/Traveler.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "T(Electro)",
    image: "/personagens/Traveler.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    id: 5,
    name: "T(Geo)",
    image: "/personagens/Traveler.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Venti",
    image: "/personagens/Venti.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Wanderer",
    image: "/personagens/Wanderer.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Xiangling",
    image: "/personagens/Xiangling.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Xiao",
    image: "/personagens/Xiao.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    id: 5,
    name: "Xingqiu",
    image: "/personagens/Xingqiu.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star4Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Xinyan",
    image: "/personagens/Xinyan.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Yae Miko",
    image: "/personagens/Yae Miko.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Yanfei",
    image: "/personagens/Yanfei.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Yaoyao",
    image: "/personagens/Yaoyao.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "Yelan",
    image: "/personagens/Yelan.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Yoimiya",
    image: "/personagens/Yoimiya.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    id: 5,
    name: "Yun Jin",
    image: "/personagens/Yun Jin.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Zhongli",
    image: "/personagens/Zhongli.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Baizhu",
    image: "/personagens/Baizhu.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    id: 5,
    name: "Kaveh",
    image: "/personagens/Kaveh.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
];
