import { Cores, ColorCard, ColorShadow } from "../../enums/styles";

export const listS = [
  {
    name: "Alhaitham",
    image: "/personagens/Alhaitham.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Ayato",
    image: "/personagens/Ayato.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Candace",
    image: "/personagens/Candace.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star4Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Collei",
    image: "/personagens/Collei.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Cyno",
    image: "/personagens/Cyno.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Dehya",
    image: "/personagens/Dehya.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Dori",
    image: "/personagens/Dori.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Faruzan",
    image: "/personagens/Faruzan.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Layla",
    image: "/personagens/Layla.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Nahida",
    image: "/personagens/Nahida.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Nilou",
    image: "/personagens/Nilou.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Tighnari",
    image: "/personagens/Tighnari.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "T(Dendro)",
    image: "/personagens/Traveler.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Kaveh",
    image: "/personagens/Kaveh.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
];
