enum Cores {
  anemo = "#75c3aa",
  dendro = "#a2c53f",
  pyro = "#d91305",
  geo = "#f5b532",
  cryo = "#89ecf6",
  electro = "#9184cb",
  hydro = "#4cc2f1",
}

export enum ColorCard {
  star4Anemo = "background-color: rgb(117,195,170);background: linear-gradient(320deg, rgba(117,195,170,1) 17%, rgba(109,23,186,1) 89%);",
  star4Dendro = "background: rgb(162,197,63);background: linear-gradient(320deg, rgba(162,197,63,1) 17%, rgba(109,23,186,1) 89%);",
  star4Pyro = "background: rgb(217,19,5);background: linear-gradient(320deg, rgba(217,19,5,1) 17%, rgba(109,23,186,1) 89%)",
  star4Geo = "background: rgb(245,181,50);background: linear-gradient(320deg, rgba(245,181,50,1) 17%, rgba(109,23,186,1) 89%);",
  star4Cryo = "background: rgb(137,236,246);background: linear-gradient(320deg, rgba(137,236,246,1) 17%, rgba(109,23,186,1) 89%);",
  star4Electro = "background: rgb(145,132,203);background: linear-gradient(320deg, rgba(145,132,203,1) 17%, rgba(109,23,186,1) 89%);",
  star4Hydro = "background: rgb(76,194,241);background: linear-gradient(320deg, rgba(76,194,241,1) 17%, rgba(109,23,186,1) 89%);",

  star5Anemo = "background: rgb(117,195,170);background: linear-gradient(320deg, rgba(117,195,170,1) 17%, rgba(249,168,37,1) 89%);",
  star5Dendro = "background: rgb(162,197,63);background: linear-gradient(320deg, rgba(162,197,63,1) 17%, rgba(109,23,186,1) 89%);",
  star5Pyro = "background: rgb(217,19,5);background: linear-gradient(320deg, rgba(217,19,5,1) 17%, rgba(249,168,37,1) 89%);",
  star5Geo = "background: rgb(245,181,50);background: linear-gradient(320deg, rgba(245,181,50,1) 17%, rgba(109,23,186,1) 89%); ",
  star5Cryo = "background: rgb(137,236,246);background: linear-gradient(320deg, rgba(137,236,246,1) 17%, rgba(109,23,186,1) 89%);",
  star5Electro = "background: rgb(145,132,203);background: linear-gradient(320deg, rgba(145,132,203,1) 17%, rgba(109,23,186,1) 89%);",
  star5Hydro = "background: rgb(76,194,241);background: linear-gradient(320deg, rgba(76,194,241,1) 17%, rgba(109,23,186,1) 89%);",
}
export const lista = [
  {
    name: "Albedo",
    image: "/personagens/Albedo.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Anemo,
  },
  {
    name: "Alhaitham",
    image: "/personagens/Alhaitham.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
  },
  {
    name: "Aloy",
    image: "/personagens/Aloy.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Amber",
    image: "/personagens/Amber.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Ayaka",
    image: "/personagens/Ayaka.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Ayato",
    image: "/personagens/Ayato.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Barbara",
    image: "/personagens/Barbara.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Beidou",
    image: "/personagens/Beidou.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Bennett",
    image: "/personagens/Bennett.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Candace",
    image: "/personagens/Candace.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Anemo,
  },
  {
    name: "Childe",
    image: "/personagens/Childe.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Chongyun",
    image: "/personagens/Chongyun.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Collei",
    image: "/personagens/Collei.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
  {
    name: "Cyno",
    image: "/personagens/Cyno.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Dehya",
    image: "/personagens/Dehya.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Diluc",
    image: "/personagens/Diluc.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Diona",
    image: "/personagens/Diona.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Dori",
    image: "/personagens/Dori.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Eula",
    image: "/personagens/Eula.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Faruzan",
    image: "/personagens/Faruzan.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Fischl",
    image: "/personagens/Fischl.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Ganyu",
    image: "/personagens/Ganyu.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Gorou",
    image: "/personagens/Gorou.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
  },
  {
    name: "Heizou",
    image: "/personagens/Heizou.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Hu Tao",
    image: "/personagens/Hu Tao.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Itto",
    image: "/personagens/Itto.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
  },
  {
    name: "Jean",
    image: "/personagens/Jean.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Kaeya",
    image: "/personagens/Kaeya.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Kazuha",
    image: "/personagens/Kazuha.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Keqing",
    image: "/personagens/Keqing.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Klee",
    image: "/personagens/Klee.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Kokomi",
    image: "/personagens/Kokomi.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Kuki Shinobu",
    image: "/personagens/Kuki Shinobu.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Layla",
    image: "/personagens/Layla.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Lisa",
    image: "/personagens/Lisa.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Mika",
    image: "/personagens/Mika.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Mona",
    image: "/personagens/Mona.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Nahida",
    image: "/personagens/Nahida.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
  {
    name: "Nilou",
    image: "/personagens/Nilou.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Ningguang",
    image: "/personagens/Ningguang.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
  },
  {
    name: "Noelle",
    image: "/personagens/Noelle.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
  },
  {
    name: "Qiqi",
    image: "/personagens/Qiqi.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Raiden",
    image: "/personagens/Raiden.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Razor",
    image: "/personagens/Razor.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Rosaria",
    image: "/personagens/Rosaria.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Sara",
    image: "/personagens/Sara.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Sayu",
    image: "/personagens/Sayu.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Shenhe",
    image: "/personagens/Shenhe.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
  },
  {
    name: "Sucrose",
    image: "/personagens/Sucrose.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Thoma",
    image: "/personagens/Thoma.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Tighnari",
    image: "/personagens/Tighnari.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
  {
    name: "T(Anemo)",
    image: "/personagens/Traveler.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "T(Dendro)",
    image: "/personagens/Traveler.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
  {
    name: "T(Electro)",
    image: "/personagens/Traveler.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "T(Geo)",
    image: "/personagens/Traveler.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
  },
  {
    name: "Venti",
    image: "/personagens/Venti.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Wanderer",
    image: "/personagens/Wanderer.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Xiangling",
    image: "/personagens/Xiangling.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Xiao",
    image: "/personagens/Xiao.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
  },
  {
    name: "Xingqiu",
    image: "/personagens/Xingqiu.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Xinyan",
    image: "/personagens/Xinyan.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Yae Miko",
    image: "/personagens/Yae Miko.png",
    element: "/elements/electro.png",
    color: Cores.electro,
  },
  {
    name: "Yanfei",
    image: "/personagens/Yanfei.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Yaoyao",
    image: "/personagens/Yaoyao.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
  {
    name: "Yelan",
    image: "/personagens/Yelan.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
  },
  {
    name: "Yoimiya",
    image: "/personagens/Yoimiya.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
  },
  {
    name: "Yun Jin",
    image: "/personagens/Yun Jin.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
  },
  {
    name: "Zhongli",
    image: "/personagens/Zhongli.png",
    element: "/elements/geo.png",
    color: Cores.geo,
  },
  {
    name: "Baizhu",
    image: "/personagens/Baizhu.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
  {
    name: "Kaveh",
    image: "/personagens/Kaveh.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
  },
];
