import { Cores, ColorCard, ColorShadow } from "../../enums/styles";

export const listL = [
  {
    name: "Baizhu",
    image: "/personagens/Baizhu.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star5Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Beidou",
    image: "/personagens/Beidou.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Childe",
    image: "/personagens/Childe.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Chongyun",
    image: "/personagens/Chongyun.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star4Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Ganyu",
    image: "/personagens/Ganyu.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Hu Tao",
    image: "/personagens/Hu Tao.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Keqing",
    image: "/personagens/Keqing.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Ningguang",
    image: "/personagens/Ningguang.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    name: "Qiqi",
    image: "/personagens/Qiqi.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Shenhe",
    image: "/personagens/Shenhe.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "T(Geo)",
    image: "/personagens/Traveler.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    name: "Xiangling",
    image: "/personagens/Xiangling.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Xiao",
    image: "/personagens/Xiao.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Xingqiu",
    image: "/personagens/Xingqiu.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star4Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Xinyan",
    image: "/personagens/Xinyan.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Yanfei",
    image: "/personagens/Yanfei.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star4Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
  {
    name: "Yaoyao",
    image: "/personagens/Yaoyao.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Yelan",
    image: "/personagens/Yelan.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    id: 5,
    name: "Yun Jin",
    image: "/personagens/Yun Jin.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    id: 5,
    name: "Zhongli",
    image: "/personagens/Zhongli.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
]