import { Cores, ColorCard, ColorShadow } from "../../enums/styles";

export const listI = [
  {
    name: "Wanderer",
    image: "/personagens/Wanderer.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Itto",
    image: "/personagens/Itto.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star5Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    name: "Gorou",
    image: "/personagens/Gorou.png",
    element: "/elements/geo.png",
    color: Cores.geo,
    ColorCard: ColorCard.star4Geo,
    ColorShadow: ColorShadow.shadowGeo,
  },
  {
    name: "Kazuha",
    image: "/personagens/Kazuha.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star5Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Ayaka",
    image: "/personagens/Ayaka.png",
    element: "/elements/cryo.png",
    color: Cores.cryo,
    ColorCard: ColorCard.star5Cryo,
    ColorShadow: ColorShadow.shadowCryo,
  },
  {
    name: "Kirara",
    image: "/personagens/Kirara.png",
    element: "/elements/dendro.png",
    color: Cores.dendro,
    ColorCard: ColorCard.star4Dendro,
    ColorShadow: ColorShadow.shadowDendro,
  },
  {
    name: "Sara",
    image: "/personagens/Sara.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Kokomi",
    image: "/personagens/Kokomi.png",
    element: "/elements/hydro.png",
    color: Cores.hydro,
    ColorCard: ColorCard.star5Hydro,
    ColorShadow: ColorShadow.shadowHydro,
  },
  {
    name: "Kuki Shinobu",
    image: "/personagens/Kuki Shinobu.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star4Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Sayu",
    image: "/personagens/Sayu.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Heizou",
    image: "/personagens/Heizou.png",
    element: "/elements/anemo.png",
    color: Cores.anemo,
    ColorCard: ColorCard.star4Anemo,
    ColorShadow: ColorShadow.shadowAnemo,
  },
  {
    name: "Raiden",
    image: "/personagens/Raiden.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "T(Electro)",
    image: "/personagens/Traveler.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Yae Miko",
    image: "/personagens/Yae Miko.png",
    element: "/elements/electro.png",
    color: Cores.electro,
    ColorCard: ColorCard.star5Electro,
    ColorShadow: ColorShadow.shadowElectro,
  },
  {
    name: "Yoimiya",
    image: "/personagens/Yoimiya.png",
    element: "/elements/pyro.png",
    color: Cores.pyro,
    ColorCard: ColorCard.star5Pyro,
    ColorShadow: ColorShadow.shadowPyro,
  },
]